apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gateway-logbeat-ds
  namespace: kube-system
  labels:
    deploy: gateway-logbeat-ds
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway-logbeat-ds
  template:
    metadata:
      labels:
        app: gateway-logbeat-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gateway
                operator: In
                values:
                - blue-gw
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - gateway-logbeat-ds
            topologyKey: kubernetes.io/hostname
      containers:
        - name: gateway-logbeat
          image: "levtea/gateway-logbeat:dev"
          imagePullPolicy: Always
          command:
            - ./entrypoint.sh
          args:
            - ./server
            - -log_dir
            - "/mnt/gateway_log/"
          volumeMounts:
          - mountPath: /mnt/gateway_log
            name: gateway-logs
      volumes:
        - name: gateway-logs
          hostPath:
            path: /run/containerd/io.containerd.runtime.v2.task/k8s.io

