apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-logbeat-deploy
  namespace: kube-system
  labels:
    deploy: gateway-logbeat-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: gateway-logbeat-pod
  template:
    metadata:
      labels:
        app: gateway-logbeat-pod
      annotations:
        fluentd.active: "true"
    spec:
      containers:
        - name: gateway-logbeat
          image: "levtea/gateway-logbeat:dev"
          imagePullPolicy: Always
          command:
            - ./entrypoint.sh
          args:
            - ./server
          volumeMounts:
            - mountPath: /mnt/gateway_log
            name: gateway-logs
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
      - name: gateway-logs
        hostPath:
          path: /run/containerd/io.containerd.runtime.v2.task/k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-logbeat-svc
  namespace: kube-system
  labels:
    service: gateway-logbeat-svc
spec:
  selector:
    app: gateway-logbeat-pod
